name: kalkulator_ubinan
description: "A minimalis calculator app for agricultural productivity estimation."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo1.png
    - assets/logo2.png
    - assets/icon/app_icon.png

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#4CAF50" # hijau dominan
  image: assets/icon/native_icon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

